# Generated by Django 5.0.3 on 2024-03-12 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='tag_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='notes.tags'),
            preserve_default=False,
        ),
    ]
