# Generated by Django 5.0.3 on 2024-03-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_tags_note_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
